CREATE TABLE anotacao
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    area_cultivo_id BIGINT,
    data_criacao    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    unidade_medida  varchar(10),
    quantidade      DOUBLE PRECISION                        NOT NULL,
    atividade_id    BIGINT                                  NOT NULL,
    insumo_id       BIGINT,
    cultura_id      BIGINT,
    CONSTRAINT pk_anotacao PRIMARY KEY (id)
);

CREATE TABLE area_cultivo
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome     VARCHAR(255)                            NOT NULL,
    local_id BIGINT,
    CONSTRAINT pk_areacultivo PRIMARY KEY (id)
);

CREATE TABLE atividade
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255)                            NOT NULL,
    descricao VARCHAR(255)                            NOT NULL,
    tipo      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_atividade PRIMARY KEY (id)
);

CREATE TABLE colheita
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    anotacao_id    BIGINT                                  NOT NULL,
    unidade_medida varchar(10)                                NOT NULL,
    quantidade     DOUBLE PRECISION                        NOT NULL,
    destino_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_colheita PRIMARY KEY (id)
);

CREATE TABLE cultura
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255)                            NOT NULL,
    categoria VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_cultura PRIMARY KEY (id)
);

CREATE TABLE destino
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_destino PRIMARY KEY (id)
);

CREATE TABLE insumo
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    produto        VARCHAR(255)                            NOT NULL,
    fornecedor     VARCHAR(255)                            NOT NULL,
    data_aquisicao TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    propriedade_id BIGINT,
    CONSTRAINT pk_insumo PRIMARY KEY (id)
);

CREATE TABLE local
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome           VARCHAR(255)                            NOT NULL,
    tipo           varchar(100)                                NOT NULL,
    area_em_metros DOUBLE PRECISION                        NOT NULL,
    quebra_vento   BOOLEAN                                 NOT NULL,
    area_sensivel  BOOLEAN                                 NOT NULL,
    observacoes    VARCHAR(255),
    propriedade_id BIGINT NOT NULL,
    CONSTRAINT pk_local PRIMARY KEY (id)
);

CREATE TABLE mecanismo_controle
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    produtor_id BIGINT NOT NULL,
    tipo        VARCHAR(255)                            NOT NULL,
    valor       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_mecanismocontrole PRIMARY KEY (id)
);

CREATE TABLE produtor
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id BIGINT            NOT NULL                      ,
    nome       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_produtor PRIMARY KEY (id)
);

CREATE TABLE produtor_propriedade
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    propriedade_id BIGINT                                  NOT NULL,
    produtor_id    BIGINT                                  NOT NULL,
    papel          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_produtorpropriedade PRIMARY KEY (id)
);

CREATE TABLE programa_comercializacao
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    produtor_id BIGINT                                  NOT NULL,
    tipo        VARCHAR(255) NOT NULL ,
    valor       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_programacomercializacao PRIMARY KEY (id)
);

CREATE TABLE propriedade
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome                  VARCHAR(255)                            NOT NULL,
    observacao            VARCHAR(255),
    cep                   VARCHAR(255)                            NOT NULL,
    cidade                VARCHAR(255)                            NOT NULL,
    estado                VARCHAR(255)                            NOT NULL,
    area_total            DOUBLE PRECISION                        NOT NULL,
    area_propria          DOUBLE PRECISION                        NOT NULL,
    area_arrendada        DOUBLE PRECISION,
    area_producao_vegetal DOUBLE PRECISION,
    CONSTRAINT pk_propriedade PRIMARY KEY (id)
);

CREATE TABLE usuario
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

ALTER TABLE colheita
    ADD CONSTRAINT uc_colheita_anotacao UNIQUE (anotacao_id);

ALTER TABLE mecanismo_controle
    ADD CONSTRAINT uc_mecanismocontrole_produtorid UNIQUE (produtor_id);

ALTER TABLE produtor
    ADD CONSTRAINT uc_produtor_usuarioid UNIQUE (usuario_id);

ALTER TABLE anotacao
    ADD CONSTRAINT FK_ANOTACAO_ON_AREACULTIVOID FOREIGN KEY (area_cultivo_id) REFERENCES area_cultivo (id);

ALTER TABLE anotacao
    ADD CONSTRAINT FK_ANOTACAO_ON_ATIVIDADEID FOREIGN KEY (atividade_id) REFERENCES atividade (id);

ALTER TABLE anotacao
    ADD CONSTRAINT FK_ANOTACAO_ON_CULTURAID FOREIGN KEY (cultura_id) REFERENCES cultura (id);

ALTER TABLE anotacao
    ADD CONSTRAINT FK_ANOTACAO_ON_INSUMOID FOREIGN KEY (insumo_id) REFERENCES insumo (id);

ALTER TABLE area_cultivo
    ADD CONSTRAINT FK_AREACULTIVO_ON_LOCALID FOREIGN KEY (local_id) REFERENCES local (id);

ALTER TABLE colheita
    ADD CONSTRAINT FK_COLHEITA_ON_ANOTACAO FOREIGN KEY (anotacao_id) REFERENCES anotacao (id);

ALTER TABLE colheita
    ADD CONSTRAINT FK_COLHEITA_ON_DESTINOID FOREIGN KEY (destino_id) REFERENCES destino (id);

ALTER TABLE insumo
    ADD CONSTRAINT FK_INSUMO_ON_PROPRIEDADEID FOREIGN KEY (propriedade_id) REFERENCES propriedade (id);

ALTER TABLE local
    ADD CONSTRAINT FK_LOCAL_ON_PROPRIEDADEID FOREIGN KEY (propriedade_id) REFERENCES propriedade (id);

ALTER TABLE mecanismo_controle
    ADD CONSTRAINT FK_MECANISMOCONTROLE_ON_PRODUTORID FOREIGN KEY (produtor_id) REFERENCES produtor (id);

ALTER TABLE produtor_propriedade
    ADD CONSTRAINT FK_PRODUTORPROPRIEDADE_ON_PRODUTORID FOREIGN KEY (produtor_id) REFERENCES produtor (id);

ALTER TABLE produtor_propriedade
    ADD CONSTRAINT FK_PRODUTORPROPRIEDADE_ON_PROPRIEDADEID FOREIGN KEY (propriedade_id) REFERENCES propriedade (id);

ALTER TABLE produtor
    ADD CONSTRAINT FK_PRODUTOR_ON_USUARIOID FOREIGN KEY (usuario_id) REFERENCES usuario (id);

ALTER TABLE programa_comercializacao
    ADD CONSTRAINT FK_PROGRAMACOMERCIALIZACAO_ON_PRODUTORID FOREIGN KEY (produtor_id) REFERENCES produtor (id);